name: Build & Create Release

on:
  push:
    # branches:
    #   - master
    #   - main
    tags:
      - "v*" # v1.0.0, v2.1.3, ...

jobs:
  build:
    name: Build & Create Release

    # define the runner
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Checkout pkcs11mod dependency repository
        uses: actions/checkout@v4
        with:
          repository: cryptera-device-security/pkcs11mod
          ref: v1.0.0 # branch
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pkcs11mod # directory to clone into

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Prepare pkcs11mod module
        working-directory: pkcs11mod
        run: |
          # Prepare pkcs11mod module
          go mod init github.com/cryptera-device-security/pkcs11mod
          go mod tidy
          go generate ./...

      - name: Build libpkcs11ks
        working-directory: ./
        run: |
          # Build the pkcs11ks library
          go mod edit -replace github.com/cryptera-device-security/pkcs11mod=./pkcs11mod
          go mod tidy

      - name: Build library
        run: |
          # Build shared library into dist/
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -buildmode=c-shared -o dist/libpkcs11ks.so .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: false
          files: |
            dist/libpkcs11ks.so
